name: "Build and Publish"

on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  fix_release_deps:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.1'
    - uses: fortran-lang/setup-fortran@v1
      # Needed for py3nj-->lie_learn-->escnn
      id: setup-fortran
      with:
        compiler: gcc
        version: 13


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pip-tools
        #      - name: Publish package
        #        uses: pypa/gh-action-pypi-publish@release/v1
